SOURCE = Main-FSAD
make:
	pdflatex $(SOURCE)
	makeglossaries $(SOURCE)
	pdflatex $(SOURCE)
	pdflatex $(SOURCE)
	pdflatex $(SOURCE)

clean:
	rm -rf  $(TARGET) *.log *.aux *.out *.ind *.idx *.ilg *.toc *.bbl *.blg *.ist *.acn *.alg *.glg *.glo *.gls *.acr




