// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using GolemStandardSummaryGen.Model;
using System.Collections.Generic;

namespace GolemStandardSummaryGen
{
    public partial class GolemStandardCheatSheet
    {
        private IDictionary<string, NamespaceSummary> m_namespaces;
        private IDictionary<string, IList<ToCEntry>> m_tocEntries;

        public GolemStandardCheatSheet(IDictionary<string, NamespaceSummary> namespaces, IDictionary<string, IList<ToCEntry>> tocEntries)
        {
            this.m_namespaces = namespaces;
            this.m_tocEntries = tocEntries;
        }
    }
    
}
