//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolemSampleApp1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GolemSampleApp1.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&amp;
        ///    (golem.srv.comp.container.docker.image=&quot;golemfactory/ffmpeg&quot;)
        ///    (golem.srv.comp.container.docker.benchmark{golemfactory/ffmpeg}&gt;300)
        ///    (golem.com.payment.scheme=&quot;after&quot;)
        ///    (golem.usage.vector=[&quot;golem.usage.duration_sec&quot;])
        ///    (golem.com.pricing.model=&quot;linear&quot;)
        ///).
        /// </summary>
        internal static string Transcoding_Demand_Negotiate {
            get {
                return ResourceManager.GetString("Transcoding_Demand_Negotiate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&amp;
        ///    (golem.srv.comp.container.docker.image=golemfactory/ffmpeg)
        ///    (golem.srv.comp.container.docker.benchmark{golemfactory/ffmpeg}&gt;300)
        ///    (golem.com.payment.scheme=after)
        ///    (golem.usage.vector=[golem.usage.duration_sec])
        ///    (golem.com.pricing.model=linear)
        ///).
        /// </summary>
        internal static string Transcoding_Demand_Start {
            get {
                return ResourceManager.GetString("Transcoding_Demand_Start", resourceCulture);
            }
        }
    }
}
