//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolemSampleProvider1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GolemSampleProvider1.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;golem&quot;: {
        ///		&quot;srv&quot;:{
        ///			&quot;comp&quot;:{
        ///				&quot;container&quot;:{
        ///					&quot;docker&quot;:{
        ///						&quot;image&quot;:[&quot;golemfactory/ffmpeg&quot;],
        ///						&quot;benchmark{golemfactory/ffmpeg}&quot;:7,
        ///						&quot;benchmark{*}&quot;:null
        ///					}
        ///				}
        ///			}
        ///		},
        ///		&quot;inf&quot;:{
        ///			&quot;cpu&quot;:{
        ///				&quot;cores&quot;:4,
        ///				&quot;threads&quot;:8
        ///			},
        ///			&quot;mem&quot;:{
        ///				&quot;gib&quot;:16
        ///			},
        ///			&quot;storage&quot;:{
        ///				&quot;gib&quot;:30
        ///			}
        ///		},
        ///		&quot;com&quot;:{
        ///			&quot;payment&quot;:{
        ///				&quot;scheme&quot;:&quot;after&quot;
        ///			},
        ///			&quot;pricing&quot;:{
        ///				&quot;model&quot;:&quot;linear&quot;,
        ///				&quot;est{*}&quot;:null
        ///			}
        ///		},
        ///		&quot;usage&quot;:{
        ///			&quot;vector&quot;:[&quot;golem.us [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Transcoding_Offer_Generic {
            get {
                return ResourceManager.GetString("Transcoding_Offer_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;golem&quot;: {
        ///		&quot;srv&quot;:{
        ///			&quot;comp&quot;:{
        ///				&quot;container&quot;:{
        ///					&quot;docker&quot;:{
        ///						&quot;image&quot;:[&quot;golemfactory/ffmpeg&quot;],
        ///						&quot;benchmark{golemfactory/ffmpeg}&quot;:7,
        ///						&quot;benchmark{*}&quot;:null
        ///					}
        ///				}
        ///			}
        ///		},
        ///		&quot;inf&quot;:{
        ///			&quot;cpu&quot;:{
        ///				&quot;cores&quot;:4,
        ///				&quot;threads&quot;:8
        ///			},
        ///			&quot;mem&quot;:{
        ///				&quot;gib&quot;:16
        ///			},
        ///			&quot;storage&quot;:{
        ///				&quot;gib&quot;:30
        ///			}
        ///		},
        ///		&quot;com&quot;:{
        ///			&quot;payment&quot;:{
        ///				&quot;scheme&quot;:&quot;after&quot;
        ///			},
        ///			&quot;pricing&quot;:{
        ///				&quot;model&quot;:&quot;linear&quot;,
        ///				&quot;coeffs&quot;:[0.3, 0],
        ///				&quot;est{*}&quot;:null
        ///			}
        ///		},
        ///		&quot;usage&quot;:{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Transcoding_Offer_Priced {
            get {
                return ResourceManager.GetString("Transcoding_Offer_Priced", resourceCulture);
            }
        }
    }
}
